name: Auto Update Repository Info

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - '.github/repo-config.json'
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Repository Description
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              description: "⏱️ Bold iOS stopwatch app with lap tracking, Bungee font, random vibrant backgrounds, and motivational quotes. Built with SwiftUI.",
              topics: [
                "ios",
                "swift",
                "swiftui",
                "stopwatch",
                "timer",
                "ios-app",
                "lap-timer",
                "bungee-font",
                "motivational-quotes",
                "xcode",
                "swift5",
                "ios17",
                "custom-fonts",
                "animation",
                "haptic-feedback"
              ]
            })